# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - working-directory: ./express
      run: npm ci
    
    - name: Npm install 
      working-directory: ./express
      run: npm install
    
    - name: Npm build 
      working-directory: ./express
      run: npm run build --if-present
    
    - name: Start Server
      working-directory: ./express/express-locallibrary-tutorial/
      run: npm start
    
    - uses: actions/checkout@v3

    - name: Build
      working-directory: ./MyLibrary
      run: swift build -v
    
    - name: Run tests
      working-directory: ./MyLibrary
      run: swift test -v
